apiVersion: v1
kind: Namespace
metadata:
  name: mem-test01
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-bomb
  namespace: mem-test01
spec:
  strategy: 
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: go-playground
  template:
    metadata:
      labels:
        app: go-playground
    spec:
      containers:
      - name: server
        image: bazdoc/mem-test-limits:1.0
        resources:
          requests:
            cpu: 1000m
            memory: 512Mi
          limits: 
            cpu: 2000m
            memory: 1024Mi         
