apiVersion: v1
kind: Namespace
metadata:
  name: ds01

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: web-app-go-daemon-set
  namespace: ds01
  labels:
    app: webservgo01
spec:
  selector:
    matchLabels:
      app: webservgo01
  template:
    metadata:
      labels:
        app: webservgo01
    spec:
      containers:
      - name: servergo-ds01
        image: bazdoc/web_on_go:1.1
        ports:
          - containerPort: 8080
            name: web01
