apiVersion: v1
kind: Namespace
metadata:
  name: ns01

---

apiVersion: v1
kind: Pod
metadata:
  name: http-server
  namespace: ns01
  labels:
   app: go_app
spec:
  nodeName: worker2
  containers:
  - name: server
    image: bazdoc/web_on_go:1.0
  - name: nginx01
    image: nginx
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort: 8080
      name: http
