apiVersion: v1
kind: Pod
metadata:
  name: http-server
  namespace: ns01
spec:
  containers:
  - name: server
    image: bazdoc/web_on_go:1.0
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort: 8080
      name: http
