apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl01
  labels:
    type: front-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      name: pod02
      type: front
  template:
    metadata:
      labels:
        name: pod02
        type: front
    spec:
      containers:
      - name: nginx-pod
        image: nginx
