apiVersion: v1
kind: Service
metadata:
  name: server-svc
  namespace: ns01
spec:
  selector:
    app: webservgo01
  type: ClusterIP
  ports:
  - name: myjob
    protocol: TCP
    port: 8080
    targetPort: 8080

