apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob01
  namespace: ns01
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron01
            image: busybox
            args: ['/bin/sh', '-c', 'date; echo Hello from the Kubcluster01']
          restartPolicy: Never
---
