apiVersion: batch/v1
kind: Job
metadata:
  name: job01
  namespace: ns01
spec:
  template:
    spec:
      containers:
      - name: echo
        image: busybox
        command: ["/bin/sh", "-c", "echo 'ping01'"]
      restartPolicy: Never
  backoffLimit: 4