apiVersion: v1
kind: Service
metadata:
  namespace: ns03
  name: server-svc
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.101
spec:
  type: LoadBalancer
  selector:
    app: webservgo01
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
