apiVersion: v1
kind: Service
metadata:
  namespace: ns02
  name: server-svc
spec:
  type: NodePort
  selector:
    app: webservgo01
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081
