apiVersion: v1
kind: Namespace
metadata:
  name: conf-map

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-file-reader
  namespace: conf-map
spec:
  strategy:
    type: RollingUpdate
  replicas: 2
  nodeName: worker2
  selector:
    matchLabels:
      app: go-file-reader
  template:
    metadata:
      labels:
        app: go-file-reader
    spec:
      containers:
      - name: reader
        image: bazdoc/file_reader_go:1.1
        command: ["./app"]
        args: ["-p", "/."]        
        volumeMounts:
        - name: config-volume
          mountPath: /some.json
          subPath: some.json
        - name: config-volume2
          mountPath: /some2.json    
          subPath: some2.json        
      volumes:
      - name: config-volume
        configMap:
          name: cm01
      - name: config-volume2
        configMap:
          name: cm02     
